# Generated by Django 5.1.4 on 2024-12-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecolor',
            name='description',
        ),
    ]
